add_task:
  description: "Add tasks to TickTick."
  fields:
    title:
      description: Title of the task to add
    content:
      description: Content of the task to add.
    project:
      description: Id of the project to add the task to. Defaults to "Inbox".
    due_date:
      description: Datetime when this task is due.
get_projects:
  description: "Get a List of all Projects and their IDs"
get_tasks:
  description: "Get tasks and their data"